trigger:
 - main

stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
       vmImage: 'ubuntu-latest'
      steps:
      - task: Maven@4
        inputs:
         mavenPomFile: 'pom.xml'
         goals: 'clean install'
