trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo "Build triggered from GitHub commit"
    displayName: "Print Commit Message"

  # Build with Maven
  - task: Maven@4
    displayName: "Build with Maven"
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'

  # Copy JAR files to artifact staging directory
  - task: CopyFiles@2
    displayName: 'Copy files to artifact staging directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/target/*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Publish the copied JAR as artifact
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: springboot-app'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'springboot-app'
      publishLocation: 'Container'
